### ISSUE TITLE
open source linux version of [hiburn for Hi3881]

### ISSUE THREAD

**Issue by nikitos1550** [koendv/hi3861_notes#3]
Hi!

Found following link:
```
There is also an open source linux version of [hiburn for Hi3881](https://github.com/OpenHisiIpCam/hiburn).
```
I do not think this util can be used for hi3861, as the tool under the link if for uboot cmd automation.
Means tool suppose that target device has working uboot and it handle it's cmd for spi flash manipulation.
It was originally created for hisilicon based ip cameras that have uboot+gnu/linux software stack.

**Comment by koendv** [comment]
OK. What do you suggest:
- change to:
```
There is also an open source linux version of [hiburn for Hi3881](https://github.com/OpenHisiIpCam/hiburn). This tool supposes the target device has a working uboot. The tool was originally created for hisilicon based ip cameras that have uboot+gnu/linux software stack."
```
- or completely drop the line "There is also an open source linux version of [hiburn for Hi3881](https://github.com/OpenHisiIpCam/hiburn)."

**Comment by nikitos1550** [comment]
I think you can drop it, as I know that it will be useless for 3861.
You can believe me, as I am author of that repo.

**Comment by nikitos1550** [comment]
P.S. Also there is mention that 3861 supports Bluetooth. Is it really true? I have never seen anything related to BLE around 3861.

**Comment by koendv** [comment]
You're right. Dropped.
